//! Parity against the pinned Python reference (tests/golden/reference.jsonl,
//! generated by scripts/parity/regenerate.sh). Every record whose decision,
//! provisional verdicts, layer scores, fired rules, skip reason or final
//! outcome differs from the reference must be listed in
//! tests/golden/allowlist.json under at least one FIX-/EXT- id, and every
//! runtime-detectable id listed for it must appear in that analysis's
//! `fixes_applied`/`ext_applied`. Stale allowlist entries also fail.
//!
//! Set CANCELLI_PARITY_REPORT=1 to print every divergence with its tags.

use std::collections::{BTreeMap, BTreeSet};

use cancelli::engine::{self, Options};
use cancelli::fixes::{self, Detection};
use serde_json::Value;

const HOME: &str = "/home/user";

fn read_corpus() -> Vec<String> {
    let text = include_str!("corpus/commands.txt");
    text.lines()
        .filter(|l| !l.trim().is_empty() && !l.trim_start().starts_with('#'))
        .map(|l| match l.strip_prefix("json:") {
            Some(j) => serde_json::from_str::<String>(j).expect("json: line"),
            None => l.to_string(),
        })
        .collect()
}

fn ours(cmd: &str) -> (Value, Vec<String>) {
    let opts = Options {
        home: HOME.into(),
        ..Options::default()
    };
    let a = engine::analyze(cmd, &opts).expect("analyze");
    let tags: Vec<String> = a
        .fixes_applied
        .iter()
        .chain(a.ext_applied.iter())
        .map(|s| s.to_string())
        .collect();
    let v = serde_json::json!({
        "decision": a.provisional.balanced.as_str(),
        "provisional": {
            "strict": a.provisional.strict.as_str(),
            "balanced": a.provisional.balanced.as_str(),
            "auto": a.provisional.auto.as_str(),
        },
        "scores": {"sem": a.scores.sem, "path": a.scores.path, "pat": a.scores.pat, "struct": a.scores.r#struct},
        "aggregate": a.aggregate,
        "fired_rules": a.fired_rules.iter().map(|r| r.id.clone()).collect::<Vec<_>>(),
        "skip_reason": a.skip_predicate,
        "final": a.r#final.as_str(),
    });
    (v, tags)
}

const FIELDS: &[&str] = &[
    "decision",
    "provisional",
    "scores",
    "aggregate",
    "fired_rules",
    "skip_reason",
    "final",
];

#[test]
fn parity_with_reference() {
    let corpus = read_corpus();
    let golden: Vec<Value> = include_str!("golden/reference.jsonl")
        .lines()
        .map(|l| serde_json::from_str(l).expect("golden line"))
        .collect();
    assert_eq!(
        corpus.len(),
        golden.len(),
        "corpus and golden out of sync: run scripts/parity/regenerate.sh"
    );

    let allow: BTreeMap<String, Value> =
        serde_json::from_str(include_str!("golden/allowlist.json")).expect("allowlist.json");
    let mut by_cmd: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for (id, entry) in &allow {
        assert!(
            fixes::entry(id).is_some(),
            "allowlist id {id} is not in the registry"
        );
        for c in entry["commands"].as_array().expect("commands array") {
            by_cmd
                .entry(c.as_str().expect("command string"))
                .or_default()
                .push(id);
        }
    }

    let report = std::env::var("CANCELLI_PARITY_REPORT").is_ok();
    let mut failures = Vec::new();
    let mut divergent = 0usize;
    let mut per_id: BTreeMap<&str, usize> = BTreeMap::new();
    let mut per_field: BTreeMap<&str, usize> = BTreeMap::new();
    let mut seen_cmds = BTreeSet::new();

    for (cmd, g) in corpus.iter().zip(&golden) {
        assert_eq!(
            g["cmd"].as_str(),
            Some(cmd.as_str()),
            "golden order mismatch"
        );
        seen_cmds.insert(cmd.as_str());
        let (o, tags) = ours(cmd);
        let diffs: Vec<&str> = FIELDS.iter().copied().filter(|f| o[*f] != g[*f]).collect();
        let listed = by_cmd.get(cmd.as_str()).cloned().unwrap_or_default();
        if diffs.is_empty() {
            if !listed.is_empty() {
                failures.push(format!(
                    "stale allowlist entry {listed:?}: {cmd:?} now matches the reference"
                ));
            }
            continue;
        }
        divergent += 1;
        for f in &diffs {
            *per_field.entry(f).or_default() += 1;
        }
        if report {
            eprintln!("DIVERGE {cmd:?}\n  fields {diffs:?}\n  tags {tags:?}\n  listed {listed:?}");
            for f in &diffs {
                eprintln!("  {f}: ref={} ours={}", g[*f], o[*f]);
            }
        }
        if listed.is_empty() {
            failures.push(format!(
                "unexplained divergence {diffs:?} (tags {tags:?}): {cmd:?}"
            ));
            continue;
        }
        for id in listed {
            *per_id.entry(id).or_default() += 1;
            let e = fixes::entry(id).expect("registry");
            if e.detection == Detection::Runtime && !tags.iter().any(|t| t == id) {
                failures.push(format!(
                    "{id} listed but not activated (tags {tags:?}): {cmd:?}"
                ));
            }
        }
    }
    for c in by_cmd.keys() {
        if !seen_cmds.contains(c) {
            failures.push(format!("allowlist command not in corpus: {c:?}"));
        }
    }
    eprintln!(
        "parity: {} records, {} identical, {} divergent; by field {:?}; by id {:?}",
        corpus.len(),
        corpus.len() - divergent,
        divergent,
        per_field,
        per_id
    );
    assert!(
        failures.is_empty(),
        "{} parity failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
