//! Mapping a Claude Code `PreToolUse` call onto Jev's context (D16), from
//! the hook payload plus the session transcript (`transcript_path`, JSONL).
//!
//! * **User request** = the genuine human prompts in the transcript: `user`
//!   records whose content is a prompt, with system-injected text removed by
//!   [`is_system_injected`], stripped and joined with `"\n\n"`.
//!   JEV-DEV-001: when the joined text exceeds 4,000 characters, the POC
//!   (`adapters._join_user_turns`) keeps the *oldest* 4,000; cancelli keeps
//!   the most recent prompt always and fills the rest of the budget with the
//!   prompts immediately before it ([`join_user_request`]).
//! * **Prior actions** = assistant `tool_use` blocks before the current one
//!   (`tool_use_id`), rendered `Name(json)` like the POC's `_call_text`;
//!   `Bash` calls render as `bash(<command>)` like the smoke gate. Tool
//!   results, assistant text and thinking are never read (reasoning-blind).
//! * **Level**: no or unreadable transcript -> L0. PreToolUse fires before
//!   the current `tool_use` is written, so when it is absent every recorded
//!   call counts as prior. Prior actions present -> L2; none -> L1, or L0
//!   without a prompt. The achieved level and why are recorded.

use std::io::BufRead;
use std::path::{Path, PathBuf};

use serde::Serialize;
use serde_json::Value;

use super::state::{Level, MAX_FIELD_CHARS, call_text, py_len};
use crate::pyre::py_strip;

/// Stripped user text starting with any of these is system-injected, not
/// typed by the human. Extend here.
pub const SYSTEM_PREFIXES: &[&str] = &[
    "Another Claude session sent a message:",
    "<task-notification>",
    "<local-command-caveat>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<command-name>",
    "<command-message>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "[Request interrupted by user",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running local commands",
];

/// User text containing any of these anywhere is system-injected. Extend
/// here.
pub const SYSTEM_MARKERS: &[&str] = &["<system-reminder>"];

/// Record-level flags that mark a `user` record as not human-typed.
pub const SYSTEM_RECORD_FLAGS: &[&str] = &["isMeta", "isCompactSummary"];

/// Is this (already stripped) user text system-injected rather than typed
/// by the human? Pure.
pub fn is_system_injected(text: &str) -> bool {
    SYSTEM_PREFIXES.iter().any(|p| text.starts_with(p))
        || SYSTEM_MARKERS.iter().any(|m| text.contains(m))
}

/// The genuine human prompts in one transcript record (usually zero or
/// one). Pure.
///
/// A prompt is a `user` record without an `isMeta`/`isCompactSummary` flag
/// (and not a sidechain, whose "user" turns are written by the parent
/// agent) whose `message.content` is either a string, or an array of `text`
/// blocks with no `tool_result` block. Each candidate is stripped (Python
/// `str.strip()`), and empty or system-injected text is dropped.
pub fn human_prompts(rec: &Value) -> Vec<String> {
    if rec.get("type").and_then(Value::as_str) != Some("user") {
        return Vec::new();
    }
    if SYSTEM_RECORD_FLAGS
        .iter()
        .chain(["isSidechain"].iter())
        .any(|f| rec.get(*f).and_then(Value::as_bool) == Some(true))
    {
        return Vec::new();
    }
    let content = rec.get("message").and_then(|m| m.get("content"));
    let candidates: Vec<&str> = match content {
        Some(Value::String(s)) => vec![s.as_str()],
        Some(Value::Array(blocks)) => {
            if blocks
                .iter()
                .any(|b| b.get("type").and_then(Value::as_str) == Some("tool_result"))
            {
                return Vec::new();
            }
            blocks
                .iter()
                .filter(|b| b.get("type").and_then(Value::as_str) == Some("text"))
                .filter_map(|b| b.get("text").and_then(Value::as_str))
                .collect()
        }
        _ => Vec::new(),
    };
    candidates
        .into_iter()
        .map(py_strip)
        .filter(|t| !t.is_empty() && !is_system_injected(t))
        .map(str::to_string)
        .collect()
}

/// One assistant `tool_use` block.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolUse {
    /// `toolu_…`.
    pub id: String,
    /// Tool name.
    pub name: String,
    /// Tool input.
    pub input: Value,
}

/// The `tool_use` blocks in one assistant record. Pure.
pub fn tool_uses(rec: &Value) -> Vec<ToolUse> {
    if rec.get("type").and_then(Value::as_str) != Some("assistant") {
        return Vec::new();
    }
    let Some(Value::Array(blocks)) = rec.get("message").and_then(|m| m.get("content")) else {
        return Vec::new();
    };
    blocks
        .iter()
        .filter(|b| b.get("type").and_then(Value::as_str) == Some("tool_use"))
        .map(|b| ToolUse {
            id: b
                .get("id")
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_string(),
            name: b
                .get("name")
                .and_then(Value::as_str)
                .unwrap_or("unknown")
                .to_string(),
            input: b.get("input").cloned().unwrap_or(Value::Null),
        })
        .collect()
}

/// Render a prior tool call: `Bash` as `bash(<command>)` (the smoke-gate /
/// ShellRisk vocabulary, and the same mapping as the proposed action), any
/// other tool as `Name(<Python json.dumps(input, sort_keys=True)>)`.
pub fn prior_call_text(t: &ToolUse) -> String {
    if t.name == "Bash"
        && let Some(cmd) = t.input.get("command").and_then(Value::as_str)
    {
        return call_text("bash", &Value::String(cmd.to_string()));
    }
    call_text(&t.name, &t.input)
}

/// What a transcript yields.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Parsed {
    /// Human prompts, oldest first.
    pub prompts: Vec<String>,
    /// Tool uses before the current one (all of them when no current id).
    pub prior: Vec<ToolUse>,
    /// Whether the current `tool_use_id` was seen.
    pub found_current: bool,
    /// Lines that were not valid JSON (e.g. a partially written last line).
    pub bad_lines: usize,
}

/// Parse transcript JSONL. Pure over its input.
pub fn parse(reader: impl BufRead, current_id: Option<&str>) -> std::io::Result<Parsed> {
    let mut p = Parsed::default();
    for line in reader.lines() {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }
        let Ok(rec) = serde_json::from_str::<Value>(&line) else {
            p.bad_lines += 1;
            continue;
        };
        p.prompts.extend(human_prompts(&rec));
        for t in tool_uses(&rec) {
            if current_id.is_some_and(|c| c == t.id) {
                p.found_current = true;
            } else if !p.found_current {
                p.prior.push(t);
            }
        }
    }
    Ok(p)
}

/// Join prompts into the user request.
///
/// Identical to the POC (`"\n\n".join`) whenever the result fits in 4,000
/// characters. Otherwise (JEV-DEV-001) the most recent prompt is always
/// kept (clipped later by the state builder if it alone exceeds 4,000,
/// exactly as the POC clips a long request), preceded by as many of the
/// immediately preceding prompts as fit whole in the 4,000-character budget
/// (separators counted). Returns the text and whether older prompts were
/// dropped.
pub fn join_user_request(prompts: &[String]) -> (String, usize) {
    let joined = prompts.join("\n\n");
    if py_len(&joined) <= MAX_FIELD_CHARS {
        return (joined, prompts.len());
    }
    let Some((last, older)) = prompts.split_last() else {
        return (String::new(), 0);
    };
    let mut kept = vec![last.as_str()];
    let mut used = py_len(last);
    for p in older.iter().rev() {
        let cost = py_len(p) + 2;
        if used + cost > MAX_FIELD_CHARS {
            break;
        }
        used += cost;
        kept.push(p);
    }
    kept.reverse();
    let n = kept.len();
    (kept.join("\n\n"), n)
}

/// Where the context comes from.
#[derive(Debug, Clone, Default)]
pub struct ContextSource {
    /// `transcript_path` from the payload (or `--transcript`).
    pub transcript_path: Option<PathBuf>,
    /// The current `tool_use_id` (None: every tool use counts as prior).
    pub tool_use_id: Option<String>,
    /// `--request TEXT`: replaces the transcript's prompts.
    pub request_override: Option<String>,
}

/// The context handed to the state builder, plus how it was obtained.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Context {
    /// Achieved level.
    pub level: Level,
    /// Why this level.
    pub level_reason: String,
    /// User request (before clipping).
    #[serde(skip)]
    pub user_request: String,
    /// Prior call texts, oldest first (before the history budget).
    #[serde(skip)]
    pub prior_actions: Vec<String>,
    /// Human prompts found.
    pub prompts_total: usize,
    /// Prompts kept in the request (< total when JEV-DEV-001 dropped some).
    pub prompts_kept: usize,
    /// Prior tool uses found.
    pub actions_total: usize,
    /// Unparseable transcript lines.
    pub bad_lines: usize,
}

fn read(path: &Path, id: Option<&str>) -> std::io::Result<Parsed> {
    let f = std::fs::File::open(path)?;
    parse(std::io::BufReader::new(f), id)
}

/// Build the context for one call.
pub fn build(src: &ContextSource) -> Context {
    let mut c = Context {
        level: Level::L0,
        level_reason: String::new(),
        user_request: String::new(),
        prior_actions: Vec::new(),
        prompts_total: 0,
        prompts_kept: 0,
        actions_total: 0,
        bad_lines: 0,
    };
    let parsed = match &src.transcript_path {
        None => {
            c.level_reason = "no transcript_path".into();
            None
        }
        Some(p) => match read(p, src.tool_use_id.as_deref()) {
            Ok(parsed) => Some(parsed),
            Err(e) => {
                c.level_reason = format!("transcript unreadable: {}", e.kind());
                None
            }
        },
    };
    let mut prompts = Vec::new();
    if let Some(p) = parsed {
        c.bad_lines = p.bad_lines;
        prompts = p.prompts;
        // PreToolUse fires before Claude Code writes the current tool_use, so
        // it is normally absent; every recorded call then precedes it.
        c.level_reason = if src.tool_use_id.is_some() && !p.found_current {
            "transcript (current tool_use not yet written; all recorded calls are prior)".into()
        } else {
            "transcript".into()
        };
        c.actions_total = p.prior.len();
        c.prior_actions = p.prior.iter().map(prior_call_text).collect();
        c.level = if c.prior_actions.is_empty() {
            Level::L1
        } else {
            Level::L2
        };
    }
    if let Some(r) = &src.request_override {
        prompts = vec![r.clone()];
        c.level_reason.push_str("; request from --request");
        if c.level == Level::L0 {
            c.level = Level::L1;
        }
    }
    c.prompts_total = prompts.len();
    let (req, kept) = join_user_request(&prompts);
    c.user_request = req;
    c.prompts_kept = kept;
    if c.level == Level::L1 && c.user_request.is_empty() {
        c.level = Level::L0;
    }
    c
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn user(content: Value) -> Value {
        json!({"type": "user", "message": {"role": "user", "content": content}})
    }

    #[test]
    fn filter_keeps_typed_prompts_only() {
        assert_eq!(
            human_prompts(&user(json!("  fix the build \n"))),
            vec!["fix the build"]
        );
        for injected in [
            "Another Claude session sent a message: hi",
            "<task-notification>done</task-notification>",
            "<local-command-caveat>Caveat: …</local-command-caveat>",
            "<command-name>/clear</command-name>",
            "please <system-reminder>be careful</system-reminder>",
            "[Request interrupted by user for tool use]",
            "   ",
        ] {
            assert!(
                human_prompts(&user(json!(injected))).is_empty(),
                "{injected}"
            );
        }
        let mut meta = user(json!("Caveat"));
        meta["isMeta"] = json!(true);
        assert!(human_prompts(&meta).is_empty());
        let mut side = user(json!("subagent task"));
        side["isSidechain"] = json!(true);
        assert!(human_prompts(&side).is_empty());
        // tool results are never prompts
        let tr = user(json!([{"type": "tool_result", "tool_use_id": "toolu_1", "content": "ok"}]));
        assert!(human_prompts(&tr).is_empty());
        // text blocks (e.g. prompt with an image)
        let tb = user(json!([{"type": "text", "text": "look at this"}, {"type": "image"}]));
        assert_eq!(human_prompts(&tb), vec!["look at this"]);
        // other record types
        for t in [
            "assistant",
            "attachment",
            "last-prompt",
            "ai-title",
            "mode",
            "permission-mode",
        ] {
            assert!(human_prompts(&json!({"type": t, "message": {"content": "x"}})).is_empty());
        }
    }

    #[test]
    fn prefixes_are_extensible_data() {
        assert!(SYSTEM_PREFIXES.iter().all(|p| is_system_injected(p)));
        assert!(!is_system_injected("please run the tests"));
    }

    fn transcript() -> String {
        [
            json!({"type": "permission-mode", "permissionMode": "default"}),
            user(json!("Run the tests")),
            json!({"type": "assistant", "message": {"content": [
                {"type": "thinking", "thinking": "SECRET THOUGHT"},
                {"type": "text", "text": "AGENT PROSE"},
                {"type": "tool_use", "id": "toolu_1", "name": "Bash",
                 "input": {"command": "pytest -q", "description": "AGENT DESCRIPTION"}}]}}),
            user(json!([{"type": "tool_result", "tool_use_id": "toolu_1", "content": "RESULT TEXT"}])),
            user(json!("<system-reminder>injected</system-reminder>")),
            json!({"type": "assistant", "message": {"content": [
                {"type": "tool_use", "id": "toolu_2", "name": "Read",
                 "input": {"file_path": "/w/a.py", "limit": 5}}]}}),
            user(json!("now clean the build dir")),
            json!({"type": "assistant", "message": {"content": [
                {"type": "tool_use", "id": "toolu_3", "name": "Bash", "input": {"command": "rm -rf build"}}]}}),
        ]
        .iter()
        .map(|v| v.to_string())
        .collect::<Vec<_>>()
        .join("\n")
            + "\n{\"type\": \"assistant\", \"message\": {\"con" // torn last line
    }

    #[test]
    fn parse_excludes_current_and_reads_no_results_or_prose() {
        let p = parse(transcript().as_bytes(), Some("toolu_3")).unwrap();
        assert!(p.found_current);
        assert_eq!(p.prompts, vec!["Run the tests", "now clean the build dir"]);
        let calls: Vec<String> = p.prior.iter().map(prior_call_text).collect();
        assert_eq!(
            calls,
            vec![
                "bash(pytest -q)",
                "Read({\"file_path\": \"/w/a.py\", \"limit\": 5})"
            ]
        );
        assert_eq!(p.bad_lines, 1);
        let all = format!("{:?}", calls);
        for leaked in [
            "SECRET THOUGHT",
            "AGENT PROSE",
            "AGENT DESCRIPTION",
            "RESULT TEXT",
        ] {
            assert!(!all.contains(leaked));
        }
    }

    #[test]
    fn levels_degrade() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("t.jsonl");
        std::fs::write(&path, transcript()).unwrap();
        let ctx = |id: Option<&str>, p: Option<PathBuf>| {
            build(&ContextSource {
                transcript_path: p,
                tool_use_id: id.map(str::to_string),
                request_override: None,
            })
        };
        let c = ctx(Some("toolu_3"), Some(path.clone()));
        assert_eq!(c.level, Level::L2);
        assert_eq!(c.prior_actions.len(), 2);
        assert_eq!(c.user_request, "Run the tests\n\nnow clean the build dir");
        // current tool use not written yet (the normal PreToolUse case):
        // every recorded call is prior
        let c = ctx(Some("toolu_9"), Some(path.clone()));
        assert_eq!(c.level, Level::L2);
        assert_eq!(c.prior_actions.len(), 3);
        assert!(c.level_reason.contains("not yet written"));
        // first call of a session: no prior actions -> L1 (f6 not asked)
        let c = ctx(Some("toolu_1"), Some(path.clone()));
        assert_eq!(c.level, Level::L1);
        assert!(c.prior_actions.is_empty());
        // missing transcript
        let c = ctx(Some("toolu_3"), Some(dir.path().join("nope.jsonl")));
        assert_eq!(c.level, Level::L0);
        assert!(c.level_reason.starts_with("transcript unreadable"));
        assert_eq!(ctx(None, None).level, Level::L0);
        // lagging with no prompt at all -> L0
        let empty = dir.path().join("e.jsonl");
        std::fs::write(&empty, "").unwrap();
        assert_eq!(ctx(Some("toolu_1"), Some(empty)).level, Level::L0);
    }

    #[test]
    fn jev_dev_001_latest_prompt_survives() {
        // Short sessions are identical to the POC join.
        let short = vec!["a".to_string(), "b".to_string()];
        assert_eq!(join_user_request(&short), ("a\n\nb".to_string(), 2));
        // POC: joined[:4000] would keep only the old 5,000-char prompt.
        let old = "o".repeat(5000);
        let mid = "m".repeat(1500);
        let latest = "delete nothing, just list the files".to_string();
        let prompts = vec![old.clone(), mid.clone(), latest.clone()];
        let poc: String = prompts.join("\n\n").chars().take(4000).collect();
        assert!(
            !poc.contains(&latest),
            "the POC drops the current instruction"
        );
        let (req, kept) = join_user_request(&prompts);
        assert!(req.ends_with(&latest));
        assert_eq!(req, format!("{mid}\n\n{latest}"));
        assert_eq!(kept, 2);
        assert!(py_len(&req) <= MAX_FIELD_CHARS);
        // A single huge latest prompt is kept (the state builder clips it).
        let huge = vec!["x".to_string(), "y".repeat(6000)];
        let (req, kept) = join_user_request(&huge);
        assert_eq!((req.len(), kept), (6000, 1));
    }
}
